services:
  locohub-next:
    container_name: locohub-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    env_file:
      - .env.local
    environment:
      - PORT=3000
      # API URLs are automatically loaded from .env.local file
      # No need to specify them here - env_file handles it
    volumes:
      - ./:/usr/src/locohub-next
    working_dir: /usr/src/locohub-next
    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "rm -rf dist && yarn && yarn run build && yarn run start"

networks:
  monorepo-network:
    external: true
    name: locohub_monorepo-network
# locohub-next localhost:4000 <=> container:3000
# locohub-api localhost:4001 <=> container:3007
# locohub-batch localhost:4002 <=> container:3008

