# version: '3.3'

# services:
#   locohub-next:
#     container_name: locohub-next
#     restart: always
#     image: node:20.10.0
#     ports:
#       - 4000:3000
#     environment:
#       - PORT=3000
#     volumes:
#       - ./:/usr/src/locohub-next
#     working_dir: /usr/src/locohub-next

#     networks:
#       - client-network

#     # FOR PRODUCTION
#     command: bash -c "yarn && yarn run build && yarn run start"

# networks:
#   client-network:
#     driver: bridge
# # locohub-next localhost:4000 <=> container:3000
# # locohub-api localhost:4001 <=> container:3007
# # locohub-batch localhost:4002 <=> container:3008

