services:
  locohub-next:
    container_name: locohub-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    env_file:
      - .env.local
    environment:
      - PORT=3000
      # Override API URLs if needed - Browser will use server IP:4001 (mapped from backend container port 3007)
      # These are used by Next.js during build and runtime
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://72.61.126.236:4001}
      - REACT_APP_API_GRAPHQL_URL=${REACT_APP_API_GRAPHQL_URL:-http://72.61.126.236:4001/graphql}
      - REACT_APP_API_WS=${REACT_APP_API_WS:-ws://72.61.126.236:4001}
    volumes:
      - ./:/usr/src/locohub-next
    working_dir: /usr/src/locohub-next
    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  monorepo-network:
    external: true
    name: locohub_monorepo-network
# locohub-next localhost:4000 <=> container:3000
# locohub-api localhost:4001 <=> container:3007
# locohub-batch localhost:4002 <=> container:3008

